spring:
  application:
    name: f1aipredict
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.96.110.22}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:f1_ai_predict}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lbz206718
    driver-class-name: com.mysql.cj.jdbc.Driver
